CREATE DATABASE IF NOT EXISTS SIGMA_MOTORS;
USE SIGMA_MOTORS;

--  TABLE 1: BRANDS

CREATE TABLE BRANDS
(
BRAND_ID INT PRIMARY KEY AUTO_INCREMENT,
BRAND_NAME VARCHAR(50) NOT NULL,
COUNTRY_OF_ORIGIN VARCHAR(50),
IS_ACTIVE BOOL NOT NULL
);
--  TABLE 2: MODELS

CREATE TABLE MODELS
(
MODEL_ID INT PRIMARY KEY AUTO_INCREMENT,
BRAND_ID INT,
MODEL_NAME VARCHAR(50) NOT NULL,
BODY_TYPE VARCHAR(50),
ENGINE_DISPLACEMENT INT,
IS_ACTIVE BOOL NOT NULL,
FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID)
);
--  TABLE 3: VARIENTS

CREATE TABLE VARIENTS
(
VARIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
MODEL_ID INT,
VARIENT_NAME VARCHAR(50),
TRANSMISSION_TYPE VARCHAR(50),
FUEL_TYPE VARCHAR(50),
IS_ACTIVE BOOL NOT NULL,
FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID)
);
--  TABLE 4: VEHICLE

CREATE TABLE VEHICLE
(
VEHICLE_ID INT PRIMARY KEY AUTO_INCREMENT,
BRAND_ID INT,
MODEL_ID INT,
VARIENT_ID INT,
REGISTRATION_NUMBER VARCHAR(20) UNIQUE,
COLOUR VARCHAR(20),
MANUFACTURE_YEAR YEAR,
PRICE DECIMAL(10,2) NOT NULL,   
STATUS VARCHAR(50),
FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID),
FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID),
FOREIGN KEY (VARIENT_ID) REFERENCES VARIENTS(VARIENT_ID)
);
--  TABLE 5: EMPLOYEE

CREATE TABLE EMPLOYEE
(
EMPLOYEE_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
CNIC VARCHAR(13)  UNIQUE NOT NULL,
ROLE VARCHAR(20),
LOGIN_ID VARCHAR(50)  UNIQUE NOT NULL,
PASSWORD VARCHAR(50)  NOT NULL,
IS_ACTIVE BOOL
);

USE SIGMA_MOTORS;
INSERT INTO EMPLOYEE(EMPLOYEE_ID,NAME,CNIC, ROLE,LOGIN_ID, PASSWORD, IS_ACTIVE)
VALUES(699,"Ali", "3520251179991","admin","admin1","1234",1);

--  TABLE 6: CUSTOMER

CREATE TABLE CUSTOMER
(
CUSTOMER_ID  INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
CNIC VARCHAR(13)  UNIQUE NOT NULL,
PHONE_NUMBER VARCHAR(11)  NOT NULL,
EMAIL VARCHAR(255),
ADDRESS VARCHAR(50),
CONSTRAINT CHECK_EMAIL_FORMAT CHECK (EMAIL LIKE '%_@__%.__%')
);
--  TABLE 7: SUPPLIER

CREATE TABLE SUPPLIER
(
SUPPLIER_ID  INT PRIMARY KEY AUTO_INCREMENT,
COMPANY_NAME VARCHAR(50) UNIQUE NOT NULL,
PHONE_NUMBER VARCHAR(11) NOT NULL,
NTN VARCHAR(20),
ADDRESS VARCHAR(50),
IS_ACTIVE BOOL
);
--  TABLE 8: PURCHASE_ORDERS

CREATE TABLE PURCHASE_ORDERS
(
PURCHASE_ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
VEHICLE_ID INT,
SUPPLIER_ID INT,
EMPLOYEE_ID INT,
PRICE DECIMAL(10,2) NOT NULL,
PURCHASE_DATE DATE,
STATUS VARCHAR(20),
FOREIGN KEY (VEHICLE_ID)  REFERENCES VEHICLE(VEHICLE_ID),
FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
--  TABLE 9: SALE_TRANSCTION

CREATE TABLE SALE_TRANSCTION
(
SALE_ID INT PRIMARY KEY AUTO_INCREMENT,
VEHICLE_ID INT,
CUSTOMER_ID INT,
EMPLOYEE_ID INT,
EMPLOYEE_NAME VARCHAR(100),
PRICE DECIMAL(10,2),
DISCOUNT DECIMAL(10,2) DEFAULT 0,
SALE_DATE DATE,
PAYMENT_STATUS VARCHAR(50),
PAYMENT_METHOD VARCHAR(50),
FOREIGN KEY (VEHICLE_ID)  REFERENCES VEHICLE(VEHICLE_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);
--  TABLE 10: GATE_PASSES

CREATE TABLE GATE_PASSES
(
    GATE_PASS_ID INT PRIMARY KEY AUTO_INCREMENT,
    VEHICLE_ID   INT,
    SALE_ID      INT,
    EMPLOYEE_ID  INT,
    TIMESTAMP    DATETIME,
    QR_DATA      VARCHAR(50)
);
--  TABLE 11: HARDWARE_AUDIT_LOGS

CREATE TABLE HARDWARE_AUDIT_LOGS
(
LOG_ID INT PRIMARY KEY AUTO_INCREMENT,
EMPLOYEE_ID INT,
VEHICLE_ID INT,
LOG_TYPE VARCHAR(50),
DEVICE_ID INT,
EVENT_DATA VARCHAR(50)
);
--  TABLE 12: INVOICES  (new table)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE INVOICES
(
INVOICE_ID INT PRIMARY KEY AUTO_INCREMENT,
SALE_ID INT NOT NULL,
CUSTOMER_ID INT NOT NULL,
VEHICLE_ID INT NOT NULL,
EMPLOYEE_ID INT NOT NULL,
INVOICE_DATE DATE NOT NULL,
TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
DISCOUNT DECIMAL(12,2) DEFAULT 0,
NET_AMOUNT DECIMAL(12,2) NOT NULL,
STATUS VARCHAR(50) DEFAULT 'Payment Pending',
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (SALE_ID) REFERENCES SALE_TRANSCTION(SALE_ID),
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
FOREIGN KEY (VEHICLE_ID)  REFERENCES VEHICLE(VEHICLE_ID),
FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

--  Sample Data Insertion 

INSERT INTO BRANDS (BRAND_ID, BRAND_NAME, COUNTRY_OF_ORIGIN, IS_ACTIVE) VALUES
(1, 'Toyota', 'Japan', 1),
(2, 'Honda', 'Japan', 1),
(3, 'Hyundai', 'South Korea', 1);

INSERT INTO MODELS (MODEL_ID, BRAND_ID, MODEL_NAME, BODY_TYPE, ENGINE_DISPLACEMENT, IS_ACTIVE) VALUES
(1, 1, 'Corolla', 'Sedan', 1800, 1),
(2, 2, 'Civic',   'Sedan', 1500, 1),
(3, 3, 'Elantra', 'Sedan', 1600, 1);

INSERT INTO VARIENTS (VARIENT_ID, MODEL_ID, VARIENT_NAME, TRANSMISSION_TYPE, FUEL_TYPE, IS_ACTIVE) VALUES
(1, 1, 'Altis 1.8 CVT', 'Auto', 'Petrol', 1),
(2, 2, 'Oriel Turbo', 'Auto', 'Petrol', 1),
(3, 3, 'GLS', 'Auto', 'Petrol', 1);

INSERT INTO VEHICLE (VEHICLE_ID, BRAND_ID, MODEL_ID, VARIENT_ID, REGISTRATION_NUMBER, COLOUR, MANUFACTURE_YEAR, PRICE, STATUS) VALUES
(1, 1, 1, 1, 'LHR-2024-001', 'Super White', 2024, 7500000, 'Available'),
(2, 2, 2, 2, 'LHR-2024-002', 'Crystal Black', 2024, 8500000, 'Available'),
(3, 3, 3, 3, 'FSD-2023-003', 'Silver', 2023, 6800000, 'Available'),
(4, 1, 1, 1,  NULL, 'Attitude Black',  2024, 7600000, 'Sold');

INSERT INTO EMPLOYEE (EMPLOYEE_ID, NAME, CNIC, ROLE, LOGIN_ID, PASSWORD, IS_ACTIVE) VALUES
(55, 'Abdullah Shahid', '3310050000001', 'Admin', 'admen', '1234', 1);
USE SIGMA_MOTORS;
INSERT INTO EMPLOYEE (EMPLOYEE_ID, NAME, CNIC, ROLE, LOGIN_ID, PASSWORD, IS_ACTIVE) VALUES
(566, 'Abdullah Shahid', '3310055000001', 'Admin', 'admin', '1234', 1);

INSERT INTO CUSTOMER (CUSTOMER_ID, NAME, CNIC, PHONE_NUMBER, EMAIL, ADDRESS) VALUES
(1, 'Rana Habib', '3310022222222', '03007654321', 'habib@sigma.com', 'Faisalabad');

INSERT INTO SUPPLIER (SUPPLIER_ID, COMPANY_NAME, PHONE_NUMBER, NTN, ADDRESS, IS_ACTIVE) VALUES
(1, 'Indus Motors', '02111111111', 'NTN-12345', 'Karachi', 1);

INSERT INTO SALE_TRANSCTION (SALE_ID, VEHICLE_ID, CUSTOMER_ID, EMPLOYEE_ID, EMPLOYEE_NAME, PRICE, DISCOUNT, SALE_DATE, PAYMENT_STATUS, PAYMENT_METHOD) VALUES
(1, 4, 1, 55, 'Abdullah Shahid', 7600000, 0, '2026-05-17', 'Paid', 'Cash');

INSERT INTO PURCHASE_ORDERS (PURCHASE_ORDER_ID, VEHICLE_ID, SUPPLIER_ID, EMPLOYEE_ID, PRICE, PURCHASE_DATE, STATUS) VALUES
(1, 1, 1, 55, 7200000, '2026-05-17', 'Completed');

--  AUTO_INCREMENT RESET
ALTER TABLE BRANDS           AUTO_INCREMENT = 4;
ALTER TABLE MODELS           AUTO_INCREMENT = 4;
ALTER TABLE VARIENTS         AUTO_INCREMENT = 4;
ALTER TABLE VEHICLE          AUTO_INCREMENT = 5;
ALTER TABLE EMPLOYEE         AUTO_INCREMENT = 56;
ALTER TABLE CUSTOMER         AUTO_INCREMENT = 2;
ALTER TABLE SUPPLIER         AUTO_INCREMENT = 2;
ALTER TABLE PURCHASE_ORDERS  AUTO_INCREMENT = 2;
ALTER TABLE SALE_TRANSCTION  AUTO_INCREMENT = 2;


USE SIGMA_MOTORS;

SELECT BRAND_NAME, MODEL_NAME, VARIENT_NAME, PRICE 
FROM VEHICLE
JOIN BRANDS USING (BRAND_ID)
JOIN MODELS USING (MODEL_ID)
JOIN VARIENTS USING (VARIENT_ID)
WHERE STATUS = 'Sold';